# Generated by Django 6.0.6 on 2026-07-13 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Ady')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Ady')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Tekst')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Surat')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Doran wagty')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Uytgan wagty')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publikasiya')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='women.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Pornstar',
                'verbose_name_plural': 'PornStars',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
